export const INTERACTIVE_ROLES = new Set([
  'button',
  'link',
  'textbox',
  'checkbox',
  'radio',
  'combobox',
  'listbox',
  'menuitem',
  'menuitemcheckbox',
  'menuitemradio',
  'option',
  'searchbox',
  'slider',
  'spinbutton',
  'switch',
  'tab',
  'treeitem',
]);

export const CONTENT_ROLES = new Set([
  'heading',
  'cell',
  'gridcell',
  'columnheader',
  'rowheader',
  'listitem',
  'article',
  'region',
  'main',
  'navigation',
]);

export const STRUCTURAL_ROLES = new Set([
  'generic',
  'group',
  'list',
  'table',
  'row',
  'rowgroup',
  'grid',
  'treegrid',
  'menu',
  'menubar',
  'toolbar',
  'tablist',
  'tree',
  'directory',
  'document',
  'application',
  'presentation',
  'none',
]);

export const STYLE_CLASS_PATTERNS = [
  /^(flex|grid|block|inline|hidden)$/,
  /^(mt|mb|ml|mr|mx|my|pt|pb|pl|pr|px|py)-?\d*$/,
  /^(w|h|min|max)-/,
  /^(text|font|bg|border)-/,
  /^(rounded|shadow|opacity)-/,
  /^(hover|focus|active):/,
  /^(items|justify|gap|space)-/,
  /^(p|m)-\d*$/,
  /^transition/,
  /^duration/,
  /^ease/,
  /^transform/,
  /^scale|rotate|translate/,
];

export const SEMANTIC_TAGS = new Set([
  'main',
  'nav',
  'header',
  'footer',
  'article',
  'section',
  'aside',
  'form',
]);
