import type { MarketplacePlugin } from './types.js';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createJiti } from 'jiti';

const PLUGIN_REPO = 'dyyz1993/agent-browser-plugins';

export async function publishPlugin(
  pluginDir?: string
): Promise<{ prUrl: string; entry: MarketplacePlugin }> {
  const dir = path.resolve(pluginDir ?? process.cwd());

  const pkgPath = path.join(dir, 'package.json');
  if (!fs.existsSync(pkgPath)) {
    throw new Error(`No package.json found in ${dir}`);
  }
  const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as Record<string, unknown>;

  if (!pkg.name || !String(pkg.name).startsWith('agent-browser-plugin-')) {
    throw new Error('package.json "name" must start with "agent-browser-plugin-"');
  }

  const jiti = createJiti(import.meta.url, { interopDefault: true });
  let mod: unknown;
  const entryCandidates = ['index.ts', 'index.js', 'src/index.ts'];
  let loaded = false;
  for (const candidate of entryCandidates) {
    const fullPath = path.join(dir, candidate);
    if (fs.existsSync(fullPath)) {
      mod = await jiti.import(fullPath);
      loaded = true;
      break;
    }
  }
  if (!loaded) {
    throw new Error(`No plugin entry file found (tried ${entryCandidates.join(', ')})`);
  }

  const plugin = mod as {
    meta?: {
      name?: string;
      version?: string;
      description?: string;
      commands?: Record<string, unknown>;
    };
  };
  if (!plugin.meta?.name) throw new Error('Plugin meta.name is required');
  if (!plugin.meta?.version) throw new Error('Plugin meta.version is required');
  if (!plugin.meta?.description) throw new Error('Plugin meta.description is required');
  if (!plugin.meta?.commands || Object.keys(plugin.meta.commands).length === 0) {
    throw new Error('Plugin meta.commands must have at least one entry');
  }

  const now = new Date().toISOString();
  const commands: Record<string, { description: string; usage: string }> = {};
  for (const [cmdName, cmdMeta] of Object.entries(plugin.meta.commands)) {
    const m = cmdMeta as { description?: string; usage?: string };
    commands[cmdName] = {
      description: m.description ?? '',
      usage: m.usage ?? '',
    };
  }

  const entry: MarketplacePlugin = {
    name: plugin.meta.name,
    version: plugin.meta.version,
    description: plugin.meta.description,
    author: (pkg.author as string) ?? String(pkg.name).replace('agent-browser-plugin-', ''),
    repository: (pkg.repository as string) ?? '',
    installSource: `npm:${String(pkg.name)}@${plugin.meta.version}`,
    tags: (pkg.keywords as string[]) ?? [],
    verified: false,
    permissions: [],
    commands,
    createdAt: now,
    updatedAt: now,
  };

  const prBody = generatePrBody(entry);
  const branchName = `plugin/${entry.name}-${entry.version}`;

  const prUrl = await tryCreatePr(branchName, prBody, entry);

  return { prUrl, entry };
}

function generatePrBody(entry: MarketplacePlugin): string {
  const lines: string[] = [
    `## Plugin: ${entry.name} v${entry.version}`,
    '',
    `**Description:** ${entry.description}`,
    `**Author:** ${entry.author}`,
    `**Install:** \`${entry.installSource}\``,
    '',
    '### Commands',
    '',
  ];
  for (const [name, meta] of Object.entries(entry.commands)) {
    lines.push(`- **${name}**: ${meta.description}`);
    if (meta.usage) lines.push(`  - Usage: \`${meta.usage}\``);
  }
  if (entry.tags.length > 0) {
    lines.push('', `### Tags: ${entry.tags.join(', ')}`);
  }
  lines.push('', '---', '*This PR was auto-generated by `agent-browser plugin publish`.*');
  return lines.join('\n');
}

async function tryCreatePr(
  branchName: string,
  body: string,
  entry: MarketplacePlugin
): Promise<string> {
  const title = `feat: add plugin ${entry.name} v${entry.version}`;
  const compareUrl = `https://github.com/${PLUGIN_REPO}/compare/main...${branchName}?expand=1&title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`;

  try {
    execFileSync('gh', ['version'], { stdio: 'pipe', timeout: 5000 });

    const prUrl = execFileSync(
      'gh',
      [
        'pr',
        'create',
        '--repo',
        PLUGIN_REPO,
        '--title',
        title,
        '--body',
        body,
        '--head',
        branchName,
      ],
      { stdio: 'pipe', timeout: 30000, encoding: 'utf-8' }
    ).trim();

    return prUrl;
  } catch {
    return compareUrl;
  }
}
