import type { FlowStep } from '../types.js';
import type { ScriptExporter, ExportOptions } from './types.js';

export class CypressExporter implements ScriptExporter {
  format = 'cypress';
  extension = '.cy.ts';

  export(steps: FlowStep[], options?: ExportOptions): string {
    const lines: string[] = [];

    lines.push('// Auto-generated by agent-browser flow export');
    lines.push('// Format: Cypress');
    lines.push('');

    lines.push("describe('Recorded Flow', () => {");
    lines.push('  beforeEach(() => {');
    if (options?.baseUrl) {
      lines.push(`    cy.visit('${options.baseUrl}');`);
    }
    lines.push('  });');
    lines.push('');
    lines.push("  it('replays recorded flow', () => {");

    for (const step of steps) {
      lines.push(...this.exportStep(step));
    }

    lines.push('  });');
    lines.push('});');

    return lines.join('\n');
  }

  private exportStep(step: FlowStep): string[] {
    const lines: string[] = [];
    const indent = '    ';

    switch (step.action) {
      case 'navigate':
        lines.push(`${indent}cy.visit('${escape(step.url || '')}');`);
        break;

      case 'click': {
        const sel = step.selector;
        lines.push(`${indent}// Step: ${step.id}`);
        if (step.fallbackSelectors?.length) {
          lines.push(`${indent}// Fallback: ${step.fallbackSelectors.join(', ')}`);
        }
        lines.push(`${indent}cy.get('${escape(sel || '')}').click();`);
        break;
      }

      case 'fill': {
        const sel = step.selector;
        lines.push(
          `${indent}cy.get('${escape(sel || '')}').clear().type('${escape(step.value || '')}');`
        );
        break;
      }

      case 'press': {
        lines.push(`${indent}cy.get('body').type('${escape(step.value || '')}');`);
        break;
      }

      case 'scroll': {
        const amount = step.scrollAmount || 300;
        lines.push(`${indent}cy.scrollTo(0, ${amount});`);
        break;
      }

      case 'wait': {
        if (step.timeout) {
          lines.push(`${indent}cy.wait(${step.timeout});`);
        } else {
          lines.push(`${indent}cy.wait(1000);`);
        }
        break;
      }

      case 'snapshot':
        break;

      default:
        lines.push(`${indent}// TODO: unsupported action '${step.action}'`);
    }

    return lines;
  }
}

function escape(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
