import type { FlowStep, ExtractField } from '../types.js';
import type { ScriptExporter, ExportOptions } from './types.js';

export class SeleniumExporter implements ScriptExporter {
  format = 'selenium';
  extension = '.py';

  export(steps: FlowStep[], options?: ExportOptions): string {
    const lines: string[] = [];

    lines.push('# Auto-generated by agent-browser flow export');
    lines.push('# Format: Selenium (Python)');
    lines.push('');
    lines.push('from selenium import webdriver');
    lines.push('from selenium.webdriver.common.by import By');
    lines.push('from selenium.webdriver.common.keys import Keys');
    lines.push('from selenium.webdriver.support.ui import WebDriverWait');
    lines.push('from selenium.webdriver.support.ui import Select');
    lines.push('from selenium.webdriver.support import expected_conditions as EC');
    lines.push('from selenium.webdriver.common.action_chains import ActionChains');
    lines.push('import time');
    lines.push('');
    lines.push('');
    lines.push('def main():');
    lines.push('    options = webdriver.ChromeOptions()');
    if (options?.headless !== false) {
      lines.push('    options.add_argument("--headless")');
    }
    lines.push('    driver = webdriver.Chrome(options=options)');
    lines.push('    wait = WebDriverWait(driver, 10)');
    lines.push('');
    lines.push('    try:');

    for (const step of steps) {
      lines.push(...this.exportStep(step));
    }

    lines.push('');
    lines.push('    finally:');
    lines.push('        driver.quit()');
    lines.push('');
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push('    main()');

    return lines.join('\n');
  }

  private exportStep(step: FlowStep): string[] {
    const lines: string[] = [];
    const indent = '        ';

    switch (step.action) {
      case 'navigate':
        lines.push(`${indent}driver.get('${escape(step.url || '')}')`);
        break;

      case 'click': {
        const sel = step.selector || '';
        lines.push(`${indent}# Step: ${step.id}`);
        if (step.fallbackSelectors?.length) {
          lines.push(`${indent}# Fallback: ${step.fallbackSelectors.join(', ')}`);
        }
        lines.push(
          `${indent}element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '${escape(
            sel
          )}')))`
        );
        lines.push(`${indent}element.click()`);
        break;
      }

      case 'fill': {
        const sel = step.selector || '';
        lines.push(
          `${indent}element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '${escape(
            sel
          )}')))`
        );
        lines.push(`${indent}element.clear()`);
        lines.push(`${indent}element.send_keys('${escape(step.value || '')}')`);
        break;
      }

      case 'press': {
        const keyMap: Record<string, string> = {
          Enter: 'Keys.ENTER',
          Tab: 'Keys.TAB',
          Escape: 'Keys.ESCAPE',
          Backspace: 'Keys.BACKSPACE',
        };
        const key = keyMap[step.value || ''] || `'${escape(step.value || '')}'`;
        lines.push(`${indent}driver.find_element(By.TAG_NAME, 'body').send_keys(${key})`);
        break;
      }

      case 'scroll': {
        const amount = step.scrollAmount || 300;
        lines.push(`${indent}driver.execute_script("window.scrollBy(0, ${amount})")`);
        break;
      }

      case 'wait': {
        if (step.timeout) {
          lines.push(`${indent}time.sleep(${step.timeout / 1000})`);
        } else {
          lines.push(`${indent}time.sleep(1)`);
        }
        break;
      }

      case 'extract': {
        const container = step.container || 'body';
        const fields = step.fields || {};
        const varName = step.outputVar || 'extracted';
        lines.push(`${indent}${varName} = []`);
        lines.push(
          `${indent}elements = driver.find_elements(By.CSS_SELECTOR, '${escape(container)}')`
        );
        lines.push(`${indent}for el in elements:`);
        const entries = Object.entries(fields);
        for (const [name, def] of entries) {
          if (typeof def === 'string') {
            lines.push(
              `${indent}    ${name} = el.find_element(By.CSS_SELECTOR, '${escape(def)}').text.strip() if el.find_elements(By.CSS_SELECTOR, '${escape(def)}') else ''`
            );
          } else {
            const ef = def as ExtractField;
            if (ef.attribute) {
              lines.push(
                `${indent}    ${name} = el.find_element(By.CSS_SELECTOR, '${escape(ef.selector)}').get_attribute('${escape(ef.attribute)}') if el.find_elements(By.CSS_SELECTOR, '${escape(ef.selector)}') else ''`
              );
            } else {
              lines.push(
                `${indent}    ${name} = el.find_element(By.CSS_SELECTOR, '${escape(ef.selector)}').text.strip() if el.find_elements(By.CSS_SELECTOR, '${escape(ef.selector)}') else ''`
              );
            }
          }
        }
        if (entries.length > 0) {
          lines.push(
            `${indent}    ${varName}.append({ ${entries.map(([n]) => `'${n}': ${n}`).join(', ')} })`
          );
        }
        break;
      }

      case 'eval': {
        const script = step.value || '';
        const varName = step.outputVar;
        if (varName) {
          lines.push(`${indent}${varName} = driver.execute_script('${escapePy(script)}')`);
        } else {
          lines.push(`${indent}driver.execute_script('${escapePy(script)}')`);
        }
        break;
      }

      case 'screenshot': {
        const file = step.file || 'screenshot.png';
        if (step.selector) {
          lines.push(
            `${indent}element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '${escape(
              step.selector
            )}')))`
          );
          lines.push(`${indent}element.screenshot('${escape(file)}')`);
        } else {
          lines.push(`${indent}driver.save_screenshot('${escape(file)}')`);
        }
        break;
      }

      case 'scrollUntil': {
        const direction = step.scrollDirection || 'down';
        const amount = step.scrollAmount || 300;
        const sign = direction === 'up' ? '-' : '';
        lines.push(`${indent}driver.execute_script("window.scrollBy(0, ${sign}${amount})")`);
        break;
      }

      case 'paginate': {
        const nextSel = step.nextSelector || '';
        if (nextSel) {
          lines.push(
            `${indent}element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '${escape(
              nextSel
            )}')))`
          );
          lines.push(`${indent}element.click()`);
        }
        break;
      }

      case 'clickPaginate': {
        const nextSel = step.nextSelector || '';
        if (nextSel) {
          lines.push(
            `${indent}element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '${escape(
              nextSel
            )}')))`
          );
          lines.push(`${indent}element.click()`);
        }
        break;
      }

      case 'forEach':
      case 'forEachItem': {
        const itemSel = step.itemSelector || step.container || '';
        const subSteps = step.subSteps || step.itemSteps || [];
        if (itemSel) {
          lines.push(
            `${indent}items = driver.find_elements(By.CSS_SELECTOR, '${escape(itemSel)}')`
          );
          lines.push(`${indent}for item in items:`);
          if (subSteps.length === 0) {
            lines.push(`${indent}    pass`);
          }
          for (const sub of subSteps) {
            const subLines = this.exportStep(sub);
            for (const line of subLines) {
              lines.push(`    ${line}`);
            }
          }
        }
        break;
      }

      case 'condition': {
        const cond = step.condition || step.conditionJs || '';
        const thenSteps = step.thenSteps || [];
        const elseSteps = step.elseSteps || [];
        if (cond) {
          lines.push(`${indent}if driver.execute_script('${escapePy(cond)}'):`);
          for (const s of thenSteps) {
            const subLines = this.exportStep(s);
            for (const line of subLines) {
              lines.push(`    ${line}`);
            }
          }
          if (elseSteps.length > 0) {
            lines.push(`${indent}else:`);
            for (const s of elseSteps) {
              const subLines = this.exportStep(s);
              for (const line of subLines) {
                lines.push(`    ${line}`);
              }
            }
          }
        }
        break;
      }

      case 'repeatWhile': {
        const loopSteps = step.loopSteps || step.subSteps || [];
        const cond = step.condition || step.conditionJs || '';
        lines.push(`${indent}while driver.execute_script('${escapePy(cond || 'true')}'):`);
        if (loopSteps.length === 0) {
          lines.push(`${indent}    break`);
        }
        for (const s of loopSteps) {
          const subLines = this.exportStep(s);
          for (const line of subLines) {
            lines.push(`    ${line}`);
          }
        }
        break;
      }

      case 'collectAll': {
        const collectSteps = step.collectSteps || step.subSteps || [];
        lines.push(`${indent}# collectAll`);
        for (const s of collectSteps) {
          lines.push(...this.exportStep(s));
        }
        break;
      }

      case 'smartExtract': {
        const config = step.smartExtractConfig;
        lines.push(`${indent}# smartExtract`);
        if (config?.container) {
          lines.push(`${indent}# container: ${escape(config.container)}`);
        }
        break;
      }

      case 'detectBlocking': {
        lines.push(`${indent}# detectBlocking - manual review needed`);
        break;
      }

      case 'humanHelp':
      case 'waitForHuman': {
        lines.push(
          `${indent}# ${step.action}: ${escape(step.intervention?.message || 'requires human intervention')}`
        );
        break;
      }

      case 'autoRecover': {
        lines.push(`${indent}# autoRecover`);
        break;
      }

      case 'captureScript': {
        lines.push(`${indent}# captureScript: ${escape(step.file || '')}`);
        break;
      }

      case 'readCapture': {
        lines.push(`${indent}# readCapture: ${escape(step.file || '')}`);
        break;
      }

      case 'captureAPI': {
        lines.push(`${indent}# captureAPI: ${escape(step.apiUrl || '')}`);
        break;
      }

      case 'readAPI': {
        lines.push(`${indent}# readAPI: ${escape(step.apiUrl || '')}`);
        break;
      }

      case 'interceptRoute': {
        const apiUrl = step.apiUrl || '';
        const mockStatus = step.mockStatus || 200;
        lines.push(`${indent}# interceptRoute: ${escape(apiUrl)} -> ${mockStatus}`);
        lines.push(`${indent}# Selenium does not support request interception natively`);
        break;
      }

      case 'removeRoute': {
        lines.push(`${indent}# removeRoute - not supported in Selenium`);
        break;
      }

      case 'formatOutput': {
        lines.push(`${indent}# formatOutput: ${escape(step.outputFormat || '')}`);
        break;
      }

      case 'deduplicate': {
        lines.push(`${indent}# deduplicate on field: ${escape(step.dedupField || '')}`);
        break;
      }

      case 'snapshot':
        break;

      default:
        lines.push(`${indent}print('Unsupported action: ${step.action}')`);
    }

    return lines;
  }
}

function escape(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function escapePy(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n');
}
