import type { FlowStep } from '../types.js';
import type { ScriptExporter, ExportOptions } from './types.js';

export class SeleniumExporter implements ScriptExporter {
  format = 'selenium';
  extension = '.py';

  export(steps: FlowStep[], options?: ExportOptions): string {
    const lines: string[] = [];

    lines.push('# Auto-generated by agent-browser flow export');
    lines.push('# Format: Selenium (Python)');
    lines.push('');
    lines.push('from selenium import webdriver');
    lines.push('from selenium.webdriver.common.by import By');
    lines.push('from selenium.webdriver.common.keys import Keys');
    lines.push('from selenium.webdriver.support.ui import WebDriverWait');
    lines.push('from selenium.webdriver.support import expected_conditions as EC');
    lines.push('import time');
    lines.push('');
    lines.push('');
    lines.push('def main():');
    lines.push('    options = webdriver.ChromeOptions()');
    if (options?.headless !== false) {
      lines.push('    options.add_argument("--headless")');
    }
    lines.push('    driver = webdriver.Chrome(options=options)');
    lines.push('    wait = WebDriverWait(driver, 10)');
    lines.push('');
    lines.push('    try:');

    for (const step of steps) {
      lines.push(...this.exportStep(step));
    }

    lines.push('');
    lines.push('    finally:');
    lines.push('        driver.quit()');
    lines.push('');
    lines.push('');
    lines.push('if __name__ == "__main__":');
    lines.push('    main()');

    return lines.join('\n');
  }

  private exportStep(step: FlowStep): string[] {
    const lines: string[] = [];
    const indent = '        ';

    switch (step.action) {
      case 'navigate':
        lines.push(`${indent}driver.get('${escape(step.url || '')}')`);
        break;

      case 'click': {
        const sel = step.selector || '';
        lines.push(`${indent}# Step: ${step.id}`);
        if (step.fallbackSelectors?.length) {
          lines.push(`${indent}# Fallback: ${step.fallbackSelectors.join(', ')}`);
        }
        lines.push(
          `${indent}element = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, '${escape(
            sel
          )}')))`
        );
        lines.push(`${indent}element.click()`);
        break;
      }

      case 'fill': {
        const sel = step.selector || '';
        lines.push(
          `${indent}element = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, '${escape(
            sel
          )}')))`
        );
        lines.push(`${indent}element.clear()`);
        lines.push(`${indent}element.send_keys('${escape(step.value || '')}')`);
        break;
      }

      case 'press': {
        const keyMap: Record<string, string> = {
          Enter: 'Keys.ENTER',
          Tab: 'Keys.TAB',
          Escape: 'Keys.ESCAPE',
          Backspace: 'Keys.BACKSPACE',
        };
        const key = keyMap[step.value || ''] || `'${escape(step.value || '')}'`;
        lines.push(`${indent}driver.find_element(By.TAG_NAME, 'body').send_keys(${key})`);
        break;
      }

      case 'scroll': {
        const amount = step.scrollAmount || 300;
        lines.push(`${indent}driver.execute_script("window.scrollBy(0, ${amount})")`);
        break;
      }

      case 'wait': {
        if (step.timeout) {
          lines.push(`${indent}time.sleep(${step.timeout / 1000})`);
        } else {
          lines.push(`${indent}time.sleep(1)`);
        }
        break;
      }

      case 'snapshot':
        break;

      default:
        lines.push(`${indent}# TODO: unsupported action '${step.action}'`);
    }

    return lines;
  }
}

function escape(str: string): string {
  return str.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
